// <auto-generated />
namespace MvcApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ljl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ljl));
        
        string IMigrationMetadata.Id
        {
            get { return "201602272051139_ljl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
