//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RotacionDocente
    {
     

        public int RotacionDocenteId { get; set; }
        public int rotacionEstudianteId { get; set; }    
        public int docenteId { get; set; }

        public string nombre { get; set; }
       
     
        public virtual RotacionEstudiante Rotacion { get; set; }

        public virtual Docente Docente { get; set; }
     
    }
}
